# Generated by Django 3.0 on 2020-12-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(related_name='question', to='Test.Question'),
        ),
    ]
