# Generated by Django 3.0 on 2020-12-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_test_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncategory',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
